// Inventario real — Sale by Saimon
// price y condition quedan en null hasta que definamos precio de venta y estado real.
window.PRODUCTS = [
  {id:17,name:"Jordan 1 Retro Low OG",variant:"Black Dark Powder Blue",category:"SNEAKERS",size:"US 9",style:"CZ0775-104",colorway:"White/Black/Dark Powder Blue",releaseDate:"27/07/2022",price:null,condition:null,image:"assets/products/jordan-1-low-og-dark-powder-blue.webp",featured:true,available:true},
  {id:16,name:"Jordan 1 Low OG",variant:"Starfish",category:"SNEAKERS",size:"US 9",style:"CZ0775-801",colorway:"Starfish/White-Black",releaseDate:"02/09/2021",price:null,condition:null,image:"assets/products/jordan-1-low-og-starfish.webp",featured:true,available:true},
  {id:15,name:"Jordan 1 Low SE",variant:"Concord",category:"SNEAKERS",size:"US 9",style:"DV1309-100",colorway:"White/Black",releaseDate:"17/01/2023",price:null,condition:null,image:"assets/products/jordan-1-low-se-concord.webp",featured:true,available:true},
  {id:14,name:"Jordan 1 Mid",variant:"Taxi",category:"SNEAKERS",size:"US 9.5",style:"554724-701",colorway:"Taxi/White-Black",releaseDate:"20/08/2022",price:null,condition:null,image:"assets/products/jordan-1-mid-taxi.webp",featured:true,available:true},
  {id:13,name:"Jordan 1 Retro High OG",variant:"Palomino",category:"SNEAKERS",size:"US 11",style:"DZ5485-020",colorway:"Black/Metallic Gold/Palomino/Sail",releaseDate:"02/09/2023",price:null,condition:null,image:"assets/products/jordan-1-high-og-palomino.jpeg",featured:true,available:true},
  {id:12,name:"Jordan 4 Retro SE",variant:"Black Canvas",category:"SNEAKERS",size:"US 9",style:"DH7138-006",colorway:"Black/Light Steel Grey/White/Fire Red",releaseDate:"05/10/2022",price:null,condition:null,image:"assets/products/jordan-4-black-canvas.jpeg",featured:false,available:true},
  {id:11,name:"Jordan 4 Retro SB",variant:"Pine Green",category:"SNEAKERS",size:"US 9",style:"DR5415-103",colorway:"Sail/Pine Green/Neutral Grey/White",releaseDate:"21/03/2023",price:null,condition:null,image:"assets/products/jordan-4-sb-pine-green.jpeg",featured:false,available:true},
  {id:10,name:"Nike Dunk Low",variant:"Chlorophyll",category:"SNEAKERS",size:"US 9",style:"DJ6188-300",colorway:"Chlorophyll/White-Vivid Green",releaseDate:"08/07/2022",price:null,condition:null,image:"assets/products/nike-dunk-low-chlorophyll.jpeg",featured:false,available:true},
  {id:9,name:"Nike Dunk Low",variant:"Championship Court Purple",category:"SNEAKERS",size:"US 9",style:"DD1391-104",colorway:"White/Court Purple",releaseDate:"05/05/2022",price:null,condition:null,image:"assets/products/nike-dunk-low-court-purple.jpeg",featured:false,available:true},
  {id:8,name:"Nike Dunk Low SE",variant:"Teddy Bear Praline",category:"SNEAKERS",size:"US 9",style:"DZ5350-288",colorway:"Praline/Desert Ocher/Hemp/Pearl White",releaseDate:"26/11/2022",price:null,condition:null,image:"assets/products/nike-dunk-low-teddy-bear.jpeg",featured:false,available:true},
  {id:7,name:"Nike SB Dunk Low",variant:"Sandy Bodecker",category:"SNEAKERS",size:"US 9",style:"FD8777-100",colorway:"White/Hyper Royal/Mean Green",releaseDate:"17/12/2022",price:null,condition:null,image:"assets/products/nike-sb-dunk-sandy-bodecker.jpeg",featured:false,available:true},
  {id:6,name:"Nike Air Max 2013",variant:"Stüssy Fossil",category:"SNEAKERS",size:"US 9",style:"DM6447-200",colorway:"Fossil/Fossil/Black",releaseDate:"12/08/2022",price:null,condition:null,image:"assets/products/nike-air-max-2013-stussy-fossil.webp",featured:false,available:true},
  {id:5,name:"Nike Air Force 1 Mid",variant:"Off-White Black",category:"SNEAKERS",size:"US 9",style:"DO6290-001",colorway:"Black/Clear Black",releaseDate:"23/06/2022",price:null,condition:null,image:"assets/products/nike-air-force-1-mid-off-white.jpeg",featured:false,available:true},
  {id:4,name:"Nike Air Max Dn SE",variant:"Bold Berry",category:"SNEAKERS",size:"US 9",style:"HQ3605-505",colorway:"Bold Berry/Hyper Violet/White/Black",releaseDate:"21/10/2024",price:null,condition:null,image:"assets/products/nike-air-max-dn-bold-berry.jpeg",featured:false,available:true},
  {id:3,name:"Balenciaga Track",variant:"White Orange",category:"SNEAKERS",size:"US 9.5",style:"542023W1GB19059",colorway:"White/Orange",releaseDate:"03/09/2018",price:null,condition:null,image:"assets/products/balenciaga-track-white-orange.jpeg",featured:false,available:true},
  {id:2,name:"Supreme × The North Face",variant:"Printed Nuptse Trompe L'oeil Jacket — Yellow",category:"ROPA",size:"XL",style:"—",colorway:"Yellow",season:"SS23",releaseDate:"09/03/2023",price:null,condition:null,image:"assets/products/supreme-tnf-nuptse-trompe-loeil-yellow.jpeg",featured:false,available:true},
  {id:1,name:"The North Face 1996 Retro Nuptse",variant:"700 Fill Packable — Earthen Copper / TNF Black",category:"ROPA",size:"L",style:"NF0A3C8D",colorway:"Earthen Copper/TNF Black",season:"FW24",releaseDate:null,price:null,condition:null,image:"assets/products/tnf-1996-retro-nuptse-earthen-copper.webp",featured:false,available:true}
];
